config/routes.rb
Rails.application.routes.draw do
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord


    def self.murah
        order(price: :desc)
    end

    def self.harga_menengah
        where('price > ?',600).where('price < ?',20000)
    end

    def self.dari_terbesar
        order(price: :desc)
    end

    def self.dari_terkecil
        order(price: :asc)
    end
end

app/models/coba.rb
class Coba < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :param_id, only: [:edit,:show, :update, :destroy]

  def index
    @books = Book.all.order(title: :asc)
  end

  def show
  end

  def new
      @book = Book.new
  end

  def create
    @book = Book.new param_permit

    if @book.save
      redirect_to books_path
    end
  end

  def edit
  end

  def update
    if @book.update param_permit
      redirect_to books_path
    else
      redirect_to books_path, notice: "buruk"
    end
  end

  def destroy
    if @book.destroy
      redirect_to books_path, notice: "Buku Berhasil Di Hapus"
    end
  end

  private

  def param_id
    @book = Book.find(params[:id])
  end

  def param_permit
    params.require(:book).permit(:title,:price,:page,:description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<%= form_for @book do |f| %>
    <%= f.label "judul" %>
    <%= f.text_field :title %>
     </br>
    <%= f.label "harga" %>
    <%= f.text_field :price %>
    </br>
    <%= f.label "page" %>
    <%= f.text_field :page %>
    </br>
    <%= f.label :description %>
    <%= f.text_field :description %>
    </br>
    <%= f.submit "tekan aku" %>
<% end %>

app/views/books/index.html.erb
    <h1><%= notice %></h1>

    <%= link_to "Tambah Data Buku" , new_book_path, class: "btn btn-primary" %>

    <table border="1" style="text-align:center;">
        <tr>
        <% no=1  %>
            <td> no </td>
            <td> judul </td>
            <td> harga </td>
            <td> halaman </td>
            <td> deskripsi </td>
            <td colspan="2">aksi </td>
        </tr>
        <%  @books.each do |book| %>
        <tr>
            <td> <%= no %> </td>
            <td> <%= book.title %> </td>
            <td> <%= book.price %> </td>
            <td> <%= book.page %> </td>
            <td> <%= book.description %> </td>
            <td> <%= link_to "edit"  ,edit_book_path(book) %> </td>
            <td> <%= link_to "delete"  ,book_path(book), method: :delete, data: {confirm: "Yakin '#{book.title}' Akan Di Hapus ?"} %> </td>
        </tr>
        <% no+=1 end %>  
    </table>

app/views/books/new.html.erb
<%= form_for @book do |f| %>
    <%= f.label "judul" %>
    <%= f.text_field :title %>
     </br>
    <%= f.label "harga" %>
    <%= f.text_field :price %>
    </br>
    <%= f.label "page" %>
    <%= f.text_field :page %>
    </br>
    <%= f.label :description %>
    <%= f.text_field :description %>
    </br>
    <%= f.submit "tekan aku" %>
<% end %>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>